services:
  - type: web
    name: mutunes
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NITRO_PRESET
        value: node-server
      - key: PORT
        value: 3000
    healthCheckPath: /
