/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlayerRouteImport } from './routes/_player'
import { Route as PlayerIndexRouteImport } from './routes/_player.index'
import { Route as PlayerSettingsRouteImport } from './routes/_player.settings'
import { Route as PlayerLibraryRouteImport } from './routes/_player.library'
import { Route as PlayerBrowseRouteImport } from './routes/_player.browse'
import { Route as PlayerPlaylistIdRouteImport } from './routes/_player.playlist.$id'
import { Route as PlayerArtistIdRouteImport } from './routes/_player.artist.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/_player',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIndexRoute = PlayerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerSettingsRoute = PlayerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerLibraryRoute = PlayerLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerBrowseRoute = PlayerBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerPlaylistIdRoute = PlayerPlaylistIdRouteImport.update({
  id: '/playlist/$id',
  path: '/playlist/$id',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerArtistIdRoute = PlayerArtistIdRouteImport.update({
  id: '/artist/$id',
  path: '/artist/$id',
  getParentRoute: () => PlayerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PlayerIndexRoute
  '/login': typeof LoginRoute
  '/browse': typeof PlayerBrowseRoute
  '/library': typeof PlayerLibraryRoute
  '/settings': typeof PlayerSettingsRoute
  '/artist/$id': typeof PlayerArtistIdRoute
  '/playlist/$id': typeof PlayerPlaylistIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/browse': typeof PlayerBrowseRoute
  '/library': typeof PlayerLibraryRoute
  '/settings': typeof PlayerSettingsRoute
  '/': typeof PlayerIndexRoute
  '/artist/$id': typeof PlayerArtistIdRoute
  '/playlist/$id': typeof PlayerPlaylistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_player': typeof PlayerRouteWithChildren
  '/login': typeof LoginRoute
  '/_player/browse': typeof PlayerBrowseRoute
  '/_player/library': typeof PlayerLibraryRoute
  '/_player/settings': typeof PlayerSettingsRoute
  '/_player/': typeof PlayerIndexRoute
  '/_player/artist/$id': typeof PlayerArtistIdRoute
  '/_player/playlist/$id': typeof PlayerPlaylistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/browse'
    | '/library'
    | '/settings'
    | '/artist/$id'
    | '/playlist/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/browse'
    | '/library'
    | '/settings'
    | '/'
    | '/artist/$id'
    | '/playlist/$id'
  id:
    | '__root__'
    | '/_player'
    | '/login'
    | '/_player/browse'
    | '/_player/library'
    | '/_player/settings'
    | '/_player/'
    | '/_player/artist/$id'
    | '/_player/playlist/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PlayerRoute: typeof PlayerRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_player': {
      id: '/_player'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_player/': {
      id: '/_player/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PlayerIndexRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/_player/settings': {
      id: '/_player/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PlayerSettingsRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/_player/library': {
      id: '/_player/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof PlayerLibraryRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/_player/browse': {
      id: '/_player/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof PlayerBrowseRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/_player/playlist/$id': {
      id: '/_player/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof PlayerPlaylistIdRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/_player/artist/$id': {
      id: '/_player/artist/$id'
      path: '/artist/$id'
      fullPath: '/artist/$id'
      preLoaderRoute: typeof PlayerArtistIdRouteImport
      parentRoute: typeof PlayerRoute
    }
  }
}

interface PlayerRouteChildren {
  PlayerBrowseRoute: typeof PlayerBrowseRoute
  PlayerLibraryRoute: typeof PlayerLibraryRoute
  PlayerSettingsRoute: typeof PlayerSettingsRoute
  PlayerIndexRoute: typeof PlayerIndexRoute
  PlayerArtistIdRoute: typeof PlayerArtistIdRoute
  PlayerPlaylistIdRoute: typeof PlayerPlaylistIdRoute
}

const PlayerRouteChildren: PlayerRouteChildren = {
  PlayerBrowseRoute: PlayerBrowseRoute,
  PlayerLibraryRoute: PlayerLibraryRoute,
  PlayerSettingsRoute: PlayerSettingsRoute,
  PlayerIndexRoute: PlayerIndexRoute,
  PlayerArtistIdRoute: PlayerArtistIdRoute,
  PlayerPlaylistIdRoute: PlayerPlaylistIdRoute,
}

const PlayerRouteWithChildren =
  PlayerRoute._addFileChildren(PlayerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PlayerRoute: PlayerRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
